# ls
alias ll='ls -alF'
alias la='ls -A'
alias l='ls -CF'
alias ltr='ls -ltr'

# tree ls
alias lst='tree -L 1'
alias lst2='tree -L 2'
alias lst3='tree -L 3'
alias lst4='tree -L 4'

# ytree
alias yt='ytree'
